#!/usr/bin/env bash

# while [[ -f hello ]]; do
#     echo 'hello file exists and is a file.'
#     sleep 1
# done
#
# echo "file is gone"

until [[ -f hello ]]; do
    echo "hello file does not exist"
    sleep 2
done

echo "Thanks for creating the file"
