#+title: Ysap Notes

Bash Scripting Course

** Introduction
REPL - Read Eval Print Loop. Terminal exists as a REPL
The terminal exists in a REPL (read, evaluate, print, loop)
Terminal is a program on the machine. Also called a Terminal Emulator.
That terminal runs a shell (abstraction layer that communicates input and output).
The same terminal can run multiple or different shells inside it. Shells are stored in the system as a application, just like the terminal.
A command runs another command; which in turn, can run more commands inside it.
Bash, file finder and terminal always opens/exists in a folder.

ls command to list the contents
touch to create a file
rm filename.extension to remove the file.
mv to change the name (note - the terminal doesn't ask for permission, it will simply overwrite the file)
rm and mv are powerful commands, can delete and move lots of files in seconds.
rm command with -i flag will interactively ask you when deleting stuff.
up and down arrows can help you navigate the commands you used earlier in the session (history).
Some people like to alias rm with rm -i so that it always runs interactively.
You can check if the command is an alias or not by using - $ alias n2
history command to see the history of commands we have on our machine.
bash has tab complete. It gives us options, if there are multiple options to complete with tab.
hidden files start with a . character. Or rather files starting with . are generally hidden.
To make them visible with ls, we use a -a flag

** Searching files and inside files
cat file.extension will print out the contents of the file on the screen
grep pattern /path/to/file.extension will print out only the lines that contain the pattern of text given to the grep command.
The pattern can also be a part of a word.
Like grep it file.txt will give out lines containing it, fit, with... you get the idea.
The quotes stop bash from reading special characters.

** We also learnt about:
$? which gives the stderr
We also learned bout bash -n filename which checks the file for any errors.
- for loops are always written in high-level syntax.
for variable in list; do
command
done

I noticed that we did not need to declare or initialize the variable before using it in bash.

** Taking input
We can use read to read command.
read -p " Message to display" variable
This gives us a prompt to enter when we echo the name.

However, when we pipe the output of echo, we override the the prompt even when it is explicitly mentioned.
Unix tricks like yes command that spams y -> This is fed into certain commands that ask for prompts.
We can use to output y by piping y from yes command and pipe it into our hello script

$1 reads out the first argument given to a command.
So if we give name=$1 and ask it to echo $name. It will print out the first argument.
$1 is the first argument then.
If the first argument is blank, it prints out the blank argument.
Similarly $@ represents all of the arguments

** Loops
The if loop is closed with a fi statement at the end.
** Functions in Bash
